# Generated by Django 4.2 on 2023-04-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_rename_person_name_person_person_lname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person_dob',
            new_name='Date_of_Birth',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='person_fname',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='image',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_desc',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_lname',
        ),
        migrations.AddField(
            model_name='person',
            name='Description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='person',
            name='Last_Name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
