# Generated by Django 4.2 on 2023-05-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0009_remove_person_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Date_of_Birth',
            field=models.DateField(),
        ),
    ]
