# Generated by Django 4.2 on 2023-05-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0010_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Criminal_Record',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='Occupation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
