# Generated by Django 4.2 on 2023-04-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='', upload_to='face/images'),
        ),
    ]
