# Generated by Django 4.2 on 2023-04-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_person_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person_name',
            new_name='person_lname',
        ),
        migrations.AddField(
            model_name='person',
            name='person_fname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
