# Generated by Django 4.2 on 2023-04-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0006_alter_person_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
