# Generated by Django 4.2 on 2023-05-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0007_alter_person_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Date_of_Birth',
            field=models.CharField(default='', max_length=20),
        ),
    ]
