# Generated by Django 4.2 on 2023-05-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0008_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Person_Id',
        ),
    ]
